// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/example.proto

// gRPC Example
//
// This example demonstrates comprehensive gRPC and Protocol Buffers features

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role enumeration
type Role int32

const (
	Role_GUEST     Role = 0
	Role_MEMBER    Role = 1
	Role_ADMIN     Role = 2
	Role_MODERATOR Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "GUEST",
		1: "MEMBER",
		2: "ADMIN",
		3: "MODERATOR",
	}
	Role_value = map[string]int32{
		"GUEST":     0,
		"MEMBER":    1,
		"ADMIN":     2,
		"MODERATOR": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_proto_example_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{0}
}

// Status enumeration
type UserStatus int32

const (
	UserStatus_INACTIVE  UserStatus = 0
	UserStatus_ACTIVE    UserStatus = 1
	UserStatus_SUSPENDED UserStatus = 2
	UserStatus_DELETED   UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
		2: "SUSPENDED",
		3: "DELETED",
	}
	UserStatus_value = map[string]int32{
		"INACTIVE":  0,
		"ACTIVE":    1,
		"SUSPENDED": 2,
		"DELETED":   3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_proto_example_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{1}
}

type Address_AddressType int32

const (
	Address_HOME  Address_AddressType = 0
	Address_WORK  Address_AddressType = 1
	Address_OTHER Address_AddressType = 2
)

// Enum value maps for Address_AddressType.
var (
	Address_AddressType_name = map[int32]string{
		0: "HOME",
		1: "WORK",
		2: "OTHER",
	}
	Address_AddressType_value = map[string]int32{
		"HOME":  0,
		"WORK":  1,
		"OTHER": 2,
	}
)

func (x Address_AddressType) Enum() *Address_AddressType {
	p := new(Address_AddressType)
	*p = x
	return p
}

func (x Address_AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Address_AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_proto_enumTypes[2].Descriptor()
}

func (Address_AddressType) Type() protoreflect.EnumType {
	return &file_proto_example_proto_enumTypes[2]
}

func (x Address_AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Address_AddressType.Descriptor instead.
func (Address_AddressType) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{2, 0}
}

type UserActivity_ActivityType int32

const (
	UserActivity_LOGIN          UserActivity_ActivityType = 0
	UserActivity_LOGOUT         UserActivity_ActivityType = 1
	UserActivity_UPDATE_PROFILE UserActivity_ActivityType = 2
	UserActivity_VIEW_PAGE      UserActivity_ActivityType = 3
	UserActivity_CLICK_BUTTON   UserActivity_ActivityType = 4
)

// Enum value maps for UserActivity_ActivityType.
var (
	UserActivity_ActivityType_name = map[int32]string{
		0: "LOGIN",
		1: "LOGOUT",
		2: "UPDATE_PROFILE",
		3: "VIEW_PAGE",
		4: "CLICK_BUTTON",
	}
	UserActivity_ActivityType_value = map[string]int32{
		"LOGIN":          0,
		"LOGOUT":         1,
		"UPDATE_PROFILE": 2,
		"VIEW_PAGE":      3,
		"CLICK_BUTTON":   4,
	}
)

func (x UserActivity_ActivityType) Enum() *UserActivity_ActivityType {
	p := new(UserActivity_ActivityType)
	*p = x
	return p
}

func (x UserActivity_ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserActivity_ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_proto_enumTypes[3].Descriptor()
}

func (UserActivity_ActivityType) Type() protoreflect.EnumType {
	return &file_proto_example_proto_enumTypes[3]
}

func (x UserActivity_ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserActivity_ActivityType.Descriptor instead.
func (UserActivity_ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{9, 0}
}

type SyncUserResponse_SyncStatus int32

const (
	SyncUserResponse_SUCCESS SyncUserResponse_SyncStatus = 0
	SyncUserResponse_FAILED  SyncUserResponse_SyncStatus = 1
	SyncUserResponse_PARTIAL SyncUserResponse_SyncStatus = 2
)

// Enum value maps for SyncUserResponse_SyncStatus.
var (
	SyncUserResponse_SyncStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "PARTIAL",
	}
	SyncUserResponse_SyncStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
		"PARTIAL": 2,
	}
)

func (x SyncUserResponse_SyncStatus) Enum() *SyncUserResponse_SyncStatus {
	p := new(SyncUserResponse_SyncStatus)
	*p = x
	return p
}

func (x SyncUserResponse_SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncUserResponse_SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_proto_enumTypes[4].Descriptor()
}

func (SyncUserResponse_SyncStatus) Type() protoreflect.EnumType {
	return &file_proto_example_proto_enumTypes[4]
}

func (x SyncUserResponse_SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncUserResponse_SyncStatus.Descriptor instead.
func (SyncUserResponse_SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{11, 0}
}

// User message with comprehensive protobuf features
type User struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role       Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=proto.Role" json:"role,omitempty"`
	CreateDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	Username   string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Oneof: demonstrate exclusive field selection
	//
	// Types that are valid to be assigned to ContactInfo:
	//
	//	*User_Email
	//	*User_Phone
	ContactInfo isUser_ContactInfo `protobuf_oneof:"contact_info"`
	// Nested message
	Profile *Profile `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	// Repeated field
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// Map field
	Metadata  map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status    UserStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=proto.UserStatus" json:"status,omitempty"`
	LastLogin *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	// Repeated nested messages
	Addresses     []*Address `protobuf:"bytes,12,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_GUEST
}

func (x *User) GetCreateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateDate
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetContactInfo() isUser_ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		if x, ok := x.ContactInfo.(*User_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		if x, ok := x.ContactInfo.(*User_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *User) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_INACTIVE
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type isUser_ContactInfo interface {
	isUser_ContactInfo()
}

type User_Email struct {
	Email string `protobuf:"bytes,5,opt,name=email,proto3,oneof"`
}

type User_Phone struct {
	Phone string `protobuf:"bytes,6,opt,name=phone,proto3,oneof"`
}

func (*User_Email) isUser_ContactInfo() {}

func (*User_Phone) isUser_ContactInfo() {}

// Nested message example
type Profile struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DisplayName string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio         string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl   string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// Nested map
	Preferences   map[string]int32 `protobuf:"bytes,5,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Profile) GetPreferences() map[string]int32 {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// Another nested message
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Address_AddressType    `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Address_AddressType" json:"type,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,7,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetType() Address_AddressType {
	if x != nil {
		return x.Type
	}
	return Address_HOME
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=proto.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_proto_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{3}
}

func (x *UserRole) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_GUEST
}

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user resource which replaces the resource on the server.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The update mask applies to the resource.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only list users created after this timestamp
	CreatedSince *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_since,json=createdSince,proto3" json:"created_since,omitempty"`
	// Only list users older than this Duration
	OlderThan *durationpb.Duration `protobuf:"bytes,2,opt,name=older_than,json=olderThan,proto3" json:"older_than,omitempty"`
	// Filter by status
	Status UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=proto.UserStatus" json:"status,omitempty"`
	// Pagination
	PageSize      int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetCreatedSince() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedSince
	}
	return nil
}

func (x *ListUsersRequest) GetOlderThan() *durationpb.Duration {
	if x != nil {
		return x.OlderThan
	}
	return nil
}

func (x *ListUsersRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_INACTIVE
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response for batch add operation
type BatchAddUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalReceived int32                  `protobuf:"varint,1,opt,name=total_received,json=totalReceived,proto3" json:"total_received,omitempty"`
	TotalAdded    int32                  `protobuf:"varint,2,opt,name=total_added,json=totalAdded,proto3" json:"total_added,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddUsersResponse) Reset() {
	*x = BatchAddUsersResponse{}
	mi := &file_proto_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddUsersResponse) ProtoMessage() {}

func (x *BatchAddUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchAddUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{8}
}

func (x *BatchAddUsersResponse) GetTotalReceived() int32 {
	if x != nil {
		return x.TotalReceived
	}
	return 0
}

func (x *BatchAddUsersResponse) GetTotalAdded() int32 {
	if x != nil {
		return x.TotalAdded
	}
	return 0
}

func (x *BatchAddUsersResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *BatchAddUsersResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchAddUsersResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// User activity for bidirectional streaming
type UserActivity struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        uint32                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityType  UserActivity_ActivityType `protobuf:"varint,2,opt,name=activity_type,json=activityType,proto3,enum=proto.UserActivity_ActivityType" json:"activity_type,omitempty"`
	Timestamp     *timestamppb.Timestamp    `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string         `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_proto_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{9}
}

func (x *UserActivity) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserActivity) GetActivityType() UserActivity_ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return UserActivity_LOGIN
}

func (x *UserActivity) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UserActivity) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type UserActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivityResponse) Reset() {
	*x = UserActivityResponse{}
	mi := &file_proto_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityResponse) ProtoMessage() {}

func (x *UserActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityResponse.ProtoReflect.Descriptor instead.
func (*UserActivityResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{10}
}

func (x *UserActivityResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserActivityResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *UserActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserActivityResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// Sync response for bidirectional streaming
type SyncUserResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserId        uint32                      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        SyncUserResponse_SyncStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.SyncUserResponse_SyncStatus" json:"status,omitempty"`
	ErrorMessage  string                      `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdatedFields []string                    `protobuf:"bytes,4,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserResponse) Reset() {
	*x = SyncUserResponse{}
	mi := &file_proto_example_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserResponse) ProtoMessage() {}

func (x *SyncUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserResponse.ProtoReflect.Descriptor instead.
func (*SyncUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{11}
}

func (x *SyncUserResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncUserResponse) GetStatus() SyncUserResponse_SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncUserResponse_SUCCESS
}

func (x *SyncUserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SyncUserResponse) GetUpdatedFields() []string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

var File_proto_example_proto protoreflect.FileDescriptor

const file_proto_example_proto_rawDesc = "" +
	"\n" +
	"\x13proto/example.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/api/annotations.proto\"\x96\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.proto.RoleR\x04role\x12;\n" +
	"\vcreate_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createDate\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x05email\x18\x05 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x06 \x01(\tH\x00R\x05phone\x12(\n" +
	"\aprofile\x18\a \x01(\v2\x0e.proto.ProfileR\aprofile\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x125\n" +
	"\bmetadata\x18\t \x03(\v2\x19.proto.User.MetadataEntryR\bmetadata\x12)\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x11.proto.UserStatusR\x06status\x129\n" +
	"\n" +
	"last_login\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12,\n" +
	"\taddresses\x18\f \x03(\v2\x0e.proto.AddressR\taddresses\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\fcontact_info\"\xa0\x02\n" +
	"\aProfile\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12>\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12A\n" +
	"\vpreferences\x18\x05 \x03(\v2\x1f.proto.Profile.PreferencesEntryR\vpreferences\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x83\x02\n" +
	"\aAddress\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.proto.Address.AddressTypeR\x04type\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"is_primary\x18\a \x01(\bR\tisPrimary\",\n" +
	"\vAddressType\x12\b\n" +
	"\x04HOME\x10\x00\x12\b\n" +
	"\x04WORK\x10\x01\x12\t\n" +
	"\x05OTHER\x10\x02\"+\n" +
	"\bUserRole\x12\x1f\n" +
	"\x04role\x18\x01 \x01(\x0e2\v.proto.RoleR\x04role\"q\n" +
	"\x11UpdateUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.proto.UserR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xf4\x01\n" +
	"\x10ListUsersRequest\x12?\n" +
	"\rcreated_since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedSince\x128\n" +
	"\n" +
	"older_than\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\tolderThan\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.proto.UserStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xd9\x01\n" +
	"\x15BatchAddUsersResponse\x12%\n" +
	"\x0etotal_received\x18\x01 \x01(\x05R\rtotalReceived\x12\x1f\n" +
	"\vtotal_added\x18\x02 \x01(\x05R\n" +
	"totalAdded\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12=\n" +
	"\fprocessed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xfc\x02\n" +
	"\fUserActivity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12E\n" +
	"\ractivity_type\x18\x02 \x01(\x0e2 .proto.UserActivity.ActivityTypeR\factivityType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12:\n" +
	"\adetails\x18\x04 \x03(\v2 .proto.UserActivity.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\fActivityType\x12\t\n" +
	"\x05LOGIN\x10\x00\x12\n" +
	"\n" +
	"\x06LOGOUT\x10\x01\x12\x12\n" +
	"\x0eUPDATE_PROFILE\x10\x02\x12\r\n" +
	"\tVIEW_PAGE\x10\x03\x12\x10\n" +
	"\fCLICK_BUTTON\x10\x04\"\xac\x01\n" +
	"\x14UserActivityResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xe7\x01\n" +
	"\x10SyncUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".proto.SyncUserResponse.SyncStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eupdated_fields\x18\x04 \x03(\tR\rupdatedFields\"2\n" +
	"\n" +
	"SyncStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02*7\n" +
	"\x04Role\x12\t\n" +
	"\x05GUEST\x10\x00\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\r\n" +
	"\tMODERATOR\x10\x03*B\n" +
	"\n" +
	"UserStatus\x12\f\n" +
	"\bINACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tSUSPENDED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xde\x05\n" +
	"\vUserService\x12H\n" +
	"\aAddUser\x12\v.proto.User\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12J\n" +
	"\tListUsers\x12\x17.proto.ListUsersRequest\x1a\v.proto.User\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users0\x01\x12T\n" +
	"\x0fListUsersByRole\x12\x0f.proto.UserRole\x1a\v.proto.User\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/users/role/{role}0\x01\x12W\n" +
	"\n" +
	"UpdateUser\x12\x18.proto.UpdateUserRequest\x1a\v.proto.User\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/api/v1/users/{user.id}\x12I\n" +
	"\aGetUser\x12\x15.proto.GetUserRequest\x1a\v.proto.User\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12Z\n" +
	"\n" +
	"DeleteUser\x12\x18.proto.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12\\\n" +
	"\rBatchAddUsers\x12\v.proto.User\x1a\x1c.proto.BatchAddUsersResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/users/batch(\x01\x12L\n" +
	"\x12UserActivityStream\x12\x13.proto.UserActivity\x1a\x1b.proto.UserActivityResponse\"\x00(\x010\x01\x127\n" +
	"\tSyncUsers\x12\v.proto.User\x1a\x17.proto.SyncUserResponse\"\x00(\x010\x01B*Z(github.com/paulstuart/grpc-example/protob\x06proto3"

var (
	file_proto_example_proto_rawDescOnce sync.Once
	file_proto_example_proto_rawDescData []byte
)

func file_proto_example_proto_rawDescGZIP() []byte {
	file_proto_example_proto_rawDescOnce.Do(func() {
		file_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_example_proto_rawDesc), len(file_proto_example_proto_rawDesc)))
	})
	return file_proto_example_proto_rawDescData
}

var file_proto_example_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_example_proto_goTypes = []any{
	(Role)(0),                        // 0: proto.Role
	(UserStatus)(0),                  // 1: proto.UserStatus
	(Address_AddressType)(0),         // 2: proto.Address.AddressType
	(UserActivity_ActivityType)(0),   // 3: proto.UserActivity.ActivityType
	(SyncUserResponse_SyncStatus)(0), // 4: proto.SyncUserResponse.SyncStatus
	(*User)(nil),                     // 5: proto.User
	(*Profile)(nil),                  // 6: proto.Profile
	(*Address)(nil),                  // 7: proto.Address
	(*UserRole)(nil),                 // 8: proto.UserRole
	(*UpdateUserRequest)(nil),        // 9: proto.UpdateUserRequest
	(*ListUsersRequest)(nil),         // 10: proto.ListUsersRequest
	(*GetUserRequest)(nil),           // 11: proto.GetUserRequest
	(*DeleteUserRequest)(nil),        // 12: proto.DeleteUserRequest
	(*BatchAddUsersResponse)(nil),    // 13: proto.BatchAddUsersResponse
	(*UserActivity)(nil),             // 14: proto.UserActivity
	(*UserActivityResponse)(nil),     // 15: proto.UserActivityResponse
	(*SyncUserResponse)(nil),         // 16: proto.SyncUserResponse
	nil,                              // 17: proto.User.MetadataEntry
	nil,                              // 18: proto.Profile.PreferencesEntry
	nil,                              // 19: proto.UserActivity.DetailsEntry
	(*timestamppb.Timestamp)(nil),    // 20: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 21: google.protobuf.FieldMask
	(*durationpb.Duration)(nil),      // 22: google.protobuf.Duration
	(*emptypb.Empty)(nil),            // 23: google.protobuf.Empty
}
var file_proto_example_proto_depIdxs = []int32{
	0,  // 0: proto.User.role:type_name -> proto.Role
	20, // 1: proto.User.create_date:type_name -> google.protobuf.Timestamp
	6,  // 2: proto.User.profile:type_name -> proto.Profile
	17, // 3: proto.User.metadata:type_name -> proto.User.MetadataEntry
	1,  // 4: proto.User.status:type_name -> proto.UserStatus
	20, // 5: proto.User.last_login:type_name -> google.protobuf.Timestamp
	7,  // 6: proto.User.addresses:type_name -> proto.Address
	20, // 7: proto.Profile.date_of_birth:type_name -> google.protobuf.Timestamp
	18, // 8: proto.Profile.preferences:type_name -> proto.Profile.PreferencesEntry
	2,  // 9: proto.Address.type:type_name -> proto.Address.AddressType
	0,  // 10: proto.UserRole.role:type_name -> proto.Role
	5,  // 11: proto.UpdateUserRequest.user:type_name -> proto.User
	21, // 12: proto.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	20, // 13: proto.ListUsersRequest.created_since:type_name -> google.protobuf.Timestamp
	22, // 14: proto.ListUsersRequest.older_than:type_name -> google.protobuf.Duration
	1,  // 15: proto.ListUsersRequest.status:type_name -> proto.UserStatus
	20, // 16: proto.BatchAddUsersResponse.processed_at:type_name -> google.protobuf.Timestamp
	3,  // 17: proto.UserActivity.activity_type:type_name -> proto.UserActivity.ActivityType
	20, // 18: proto.UserActivity.timestamp:type_name -> google.protobuf.Timestamp
	19, // 19: proto.UserActivity.details:type_name -> proto.UserActivity.DetailsEntry
	20, // 20: proto.UserActivityResponse.processed_at:type_name -> google.protobuf.Timestamp
	4,  // 21: proto.SyncUserResponse.status:type_name -> proto.SyncUserResponse.SyncStatus
	5,  // 22: proto.UserService.AddUser:input_type -> proto.User
	10, // 23: proto.UserService.ListUsers:input_type -> proto.ListUsersRequest
	8,  // 24: proto.UserService.ListUsersByRole:input_type -> proto.UserRole
	9,  // 25: proto.UserService.UpdateUser:input_type -> proto.UpdateUserRequest
	11, // 26: proto.UserService.GetUser:input_type -> proto.GetUserRequest
	12, // 27: proto.UserService.DeleteUser:input_type -> proto.DeleteUserRequest
	5,  // 28: proto.UserService.BatchAddUsers:input_type -> proto.User
	14, // 29: proto.UserService.UserActivityStream:input_type -> proto.UserActivity
	5,  // 30: proto.UserService.SyncUsers:input_type -> proto.User
	23, // 31: proto.UserService.AddUser:output_type -> google.protobuf.Empty
	5,  // 32: proto.UserService.ListUsers:output_type -> proto.User
	5,  // 33: proto.UserService.ListUsersByRole:output_type -> proto.User
	5,  // 34: proto.UserService.UpdateUser:output_type -> proto.User
	5,  // 35: proto.UserService.GetUser:output_type -> proto.User
	23, // 36: proto.UserService.DeleteUser:output_type -> google.protobuf.Empty
	13, // 37: proto.UserService.BatchAddUsers:output_type -> proto.BatchAddUsersResponse
	15, // 38: proto.UserService.UserActivityStream:output_type -> proto.UserActivityResponse
	16, // 39: proto.UserService.SyncUsers:output_type -> proto.SyncUserResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_example_proto_init() }
func file_proto_example_proto_init() {
	if File_proto_example_proto != nil {
		return
	}
	file_proto_example_proto_msgTypes[0].OneofWrappers = []any{
		(*User_Email)(nil),
		(*User_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_example_proto_rawDesc), len(file_proto_example_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_example_proto_goTypes,
		DependencyIndexes: file_proto_example_proto_depIdxs,
		EnumInfos:         file_proto_example_proto_enumTypes,
		MessageInfos:      file_proto_example_proto_msgTypes,
	}.Build()
	File_proto_example_proto = out.File
	file_proto_example_proto_goTypes = nil
	file_proto_example_proto_depIdxs = nil
}
